### PR TITLE
browserstack

### PR DESCRIPTION
**Pull request by nidhimj22**
Nemo tests can be run on BrowserStack infrastructure out of the box. Attached a doc for the same.

### CODE REVIEW

**Comment by grawk** [comment]
Hi @nidhimj22. Thanks very much for the work on this. I'm wondering, if we should add a doc to this repo called `use-cases.md`, where browserstack integration is one of the entries? That way we can keep together additional use cases.. If you agree, can you change the name of the file to `use-cases.md` and add this as the first entry?

**Comment by nidhimj22** [comment]
@grawk  that sounds good but BrowserStack is not really a use case but a service that will allow you to run your tests. Maybe we can add a page called integrations.md? 
That will give us a broader range of topics to add on the page? Feel free to change the name of the file and merge as you feel comfortable.

**Comment by grawk** [comment]
OK. I can do that. Would you feel comfortable if this paragraph was on the same page as a paragraph about other "integrations" (what I had previously called "use cases") such as Sauce Labs, PerfectoMobile and Applitools Eyes? I want to make sure I don't represent your BrowserStack example in a way that you are not comfortable.

**Comment by nidhimj22** [comment]
Yes, that would be great! :+1:

**Pull request merged**
